apiVersion: v1
kind: ConfigMap
metadata:
  name: billy-config
  namespace: billy
  labels:
    app: billy
data:
  # Finout Internal API URL
  finout-internal-api-url: "http://finout-app.prod-mirror.internal.finout.io"

  # Optional: Log level
  log-level: "INFO"
