apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-config
  namespace: billy
  labels:
    app: langfuse
data:
  NEXTAUTH_URL: "https://langfuse.internal.finout.io"
  TELEMETRY_ENABLED: "false"
  CLICKHOUSE_MIGRATION_URL: "clickhouse://langfuse-clickhouse:9000"
  CLICKHOUSE_URL: "http://langfuse-clickhouse:8123"
  CLICKHOUSE_CLUSTER_ENABLED: "false"
  LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_EVENT_UPLOAD_REGION: "auto"
  LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: "http://langfuse-minio:9000"
  LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_EVENT_UPLOAD_PREFIX: "events/"
  LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_MEDIA_UPLOAD_REGION: "auto"
  LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: "http://langfuse-minio:9000"
  LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: "media/"
  REDIS_HOST: "langfuse-redis"
  REDIS_PORT: "6379"
  REDIS_TLS_ENABLED: "false"
